apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: kill-classifier
  namespace: default
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      app: classifier
